import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { lazy, Suspense } from "react";
import Cut from "@/components/Cut";



const Logo = lazy(() => import("@/components/Logo"));
const GamePage = lazy(() => import("@/components/Gamepage"));
const Testimonial = lazy(() => import("@/components/Testimonial"));

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <Navbar />
        
        {/* Use Suspense for lazy loading */}
        <Suspense fallback={<div>Loading...</div>}>
  
        
        {children}
        </Suspense>
        <Cut />
      
    

      </body>
    </html>
  );
}
